---
title: "SOL"
author: "Mradul"
date: "15 March 2019"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Loading Libraries

```{r}



require("readxl")
library(readxl)

require("dplyr")
library(dplyr)

require("tidyr")
library(tidyr)

require("rfm")
library(rfm)

require("data.table")
library(data.table)
```
#Importing data
```{r}

cust_agg_tran <- read_excel("cust agg transaction data.xlsx")
head(cust_agg_tran)

reference_file <- read_excel("Reference file.xlsx")
head(reference_file)

```
#Combining data of reference and cust_agg_tran in one
```{r}
orignalData <- cbind(cust_agg_tran[1:49811,], reference_file)



orignalData<-
  orignalData %>% separate(Customer_Group, into=c("Customer_Group_Num", "Customer_Group"), sep= "\\.") %>% 
  separate(RevenueBand, into=c("RevenueBand_Num", "RevenueBand"), sep= "\\.")%>%
  separate(InvoiceBand, into=c("InvoiceBand_Num", "InvoiceBand"), sep= "\\.") %>%
  separate(Sampling, into=c("Sampling_Num", "Sampling"), sep= "\\.")

head(orignalData)
```
#STEP 1
```{r}

#From the Transaction Agg file, 
#select customers classified as "Active" 
#under the column Customer Group the reference file

active_Customers<- filter(orignalData, Customer_Group=="ACTIVE")
head(active_Customers)
```
#STEP 2
```{r}
#Further filter customers in step 1 for Sampling = "TG"

act_TG_Customers <- filter(active_Customers, Sampling=="TG")
DT::datatable(act_TG_Customers)
```
#STEP 3
```{r}

#From step 2, Select the customers 
#whose Avg Transaction Value (Amount per bill) is 
#above KD 25 in the transaction file
act_TG_Customers$AmountPerBill <- act_TG_Customers$TotalAmount/act_TG_Customers$billCount

act_TG_KD25_Customers <- filter(act_TG_Customers, AmountPerBill> 25.0)
head(act_TG_KD25_Customers)
```
#STEP 4
```{r}

#From step 3, Identify the customers for targeting 
#using Recency, Frequency and Monetary analysis (google it if not known). 
#Use max transaction date, bill # and Amount respectively for the 3 fields. 
#Select the best 50% customers

todaydate <- Sys.Date()

RFM_act_TG_KD25 <- data.frame(customer_id = act_TG_KD25_Customers$customer_Number, 
                              revenue = act_TG_KD25_Customers$TotalAmount,
                              most_recent_visit = act_TG_KD25_Customers$MaxTransactionDate,
                              number_of_orders = act_TG_KD25_Customers$billCount,
                              recency_days = difftime(todaydate, act_TG_KD25_Customers$MaxTransactionDate)
                              )

head(RFM_act_TG_KD25)

analysis_date <- max(act_TG_KD25_Customers$MaxTransactionDate)

### Using "rfm_table_customer()" function from rfm package

rfm_result <- rfm_table_customer(RFM_act_TG_KD25, customer_id, number_of_orders, recency_days, revenue, analysis_date)

rfm_data1<- data.frame(rfm_result$rfm)
rfm_data1<-arrange(rfm_data1, desc(rfm_data1$rfm_score))
head(rfm_data1)

############  TOP 50 % Data      #############
rfm_top50percent_data_TG <- rfm_data1[1:(nrow(rfm_data1)/2),]
head(rfm_top50percent_data_TG)

#######################################

########### VISUALIZATONS FOR RFM ANALYSIS
#The heat map shows the average monetary value for different categories of recency and frequency scores.
rfm_heatmap(rfm_result)

#to generate the distribution of monetary scores for the different combinations of frequency and recency scores.
rfm_bar_chart(rfm_result)

# To examine the relative distribution of monetary value (total revenue generated by each customer)
#recency days (days since the most recent visit for each customer) 
#frequency (transaction count for each customer)
rfm_histograms(rfm_result)

#Visualize the distribution of customers across orders.
rfm_order_dist(rfm_result)

#Recency vs Monetary Value
rfm_rm_plot(rfm_result)

#Frequency vs Monetary Value
rfm_fm_plot(rfm_result)

#Recency vs Frequency
rfm_rf_plot(rfm_result)



#############   RFM Calculation with out using the RFM package ######################
# customer_Number<- act_tg_kd25_cust_agg_tran$customer_Number
# recent_Transanction <- act_tg_kd25_cust_agg_tran$MaxTransactionDate
# bill_Count <- act_tg_kd25_cust_agg_tran$billCount
# total_Amount <- act_tg_kd25_cust_agg_tran$TotalAmount
# 
# rfm <- data.frame(customer_Number, recent_Transanction, bill_Count, total_Amount)
# head(rfm)
# 
# todaydate <- Sys.Date()
# 
# rfm <- mutate(rfm, recency = difftime(todaydate, rfm$recent_Transanction))
# head(rfm)
# rfm <- mutate(rfm, frequency = rfm$bill_Count)
# rfm$bill_Count <- as.numeric(rfm$bill_Count)
# rfm$frequency <- as.numeric(rfm$frequency)
# rfm$recency <- as.character(rfm$recency)
# rfm$recency <- as.numeric(rfm$recency)
# rfm$monetary <- rfm$total_Amount / rfm$bill_Count
# summary(rfm)
# 
# head(rfm)
# 
# df<-rfm
# 
# #start function for assigining score 1- lowest importance, 5- highest importance
# scoring <- function (df,column,r=5){
# 
#   #get the length of rows of df
#   len <- dim(df)[1]
# 
#   score <- rep(0,times=len)
# 
#   # get the quantity of rows per 1/r e.g. 1/5
#   nr <- round(len / r)
#   if (nr > 0){
# 
#     # seperate the rows by r aliquots
#     rStart <-0
#     rEnd <- 0
#     for (i in 1:r){
# 
#       #set the start row number and end row number
#       rStart = rEnd+1
# 
#       #skip one "i" if the rStart is already in the i+1 or i+2 or ...scope.
#       if (rStart> i*nr) next
# 
#       if (i == r){
#         if(rStart<=len ) rEnd <- len else next
#       }else{
#         rEnd <- i*nr
#       }
# 
#       # set the Recency score
#       score[rStart:rEnd]<- r-i+1
# 
#       # make sure the customer who have the same recency have the same score
#       s <- rEnd+1
#       if(i<r & s <= len){
#         for(u in s: len){
#           if(df[rEnd,column]==df[u,column]){
#             score[u]<- r-i+1
#             rEnd <- u
#           }else{
#             break;
#           }
#         }
# 
#       }
# 
#     }
# 
#   }
#   return(score)
# 
# }
# 
# #end of function Scoring
# head(df)
# 
# df<-df %>% arrange(df$recency)
# R_Score <- scoring(df,"recency",r=5)
# df <- cbind(df, R_Score)
# head(df)
# 
# df <- df%>% arrange(desc(df$frequency))
# head(df)
# F_Score <- scoring(df,"frequency",5)
# df <- cbind(df, F_Score)
# head(df)
# 
# 
# df <- df%>% arrange(desc(df$monetary))
# 
# M_Score <- scoring(df,"monetary",5)
# df <- cbind(df, M_Score)
# head(df)
# #order the dataframe by R_Score, F_Score, and M_Score desc
# df <- arrange(df, desc(R_Score), desc(F_Score), desc(M_Score))
# head(df)
# 
# # caculate the total score
# Total_Score <- c(100*df$R_Score + 10*df$F_Score+df$M_Score)
# 
# df <- cbind(df,Total_Score)
# glimpse(df)
# 
# 
# # get best 50% from df
# x<-length(df[,1])/2
# df1<- df[1:x, ]
# glimpse(df1)
# str(df1)
# 
##########################################################################################
```
#STEP 5
```{r}
#Select RG as a sample from the reference file 
#such that the RG selected represents the selected customers in step 4 
# (use unpaired homoskedastic t-test) such that the ratio of RG: TG is 1:10.

active_rg_KD25_data <- filter(active_Customers, Sampling=="RG" 
                              & (TotalAmount/billCount)>25.0)

head(active_rg_KD25_data)

todaydate <- Sys.Date()

RFM_act_RG_KD25 <- data.frame(customer_id = active_rg_KD25_data$customer_Number, 
                              revenue = active_rg_KD25_data$TotalAmount,
                              most_recent_visit = active_rg_KD25_data$MaxTransactionDate,
                              number_of_orders = active_rg_KD25_data$billCount,
                              recency_days = difftime(todaydate, active_rg_KD25_data$MaxTransactionDate)
)
DT::datatable(RFM_act_RG_KD25)



analysis_date <- max(active_rg_KD25_data$MaxTransactionDate)

### Using "rfm_table_customer()" function from rfm package

rfm_result_RG <- rfm_table_customer(RFM_act_RG_KD25, customer_id, number_of_orders,recency_days, revenue, analysis_date)


########### VISUALIZATONS FOR RFM ANALYSIS
#The heat map shows the average monetary value for different categories of recency and frequency scores.
rfm_heatmap(rfm_result)

#to generate the distribution of monetary scores for the different combinations of frequency and recency scores.
rfm_bar_chart(rfm_result)

# To examine the relative distribution of monetary value (total revenue generated by each customer)
#recency days (days since the most recent visit for each customer) 
#frequency (transaction count for each customer)
rfm_histograms(rfm_result)

#Visualize the distribution of customers across orders.
rfm_order_dist(rfm_result)

#Recency vs Monetary Value
rfm_rm_plot(rfm_result)

#Frequency vs Monetary Value
rfm_fm_plot(rfm_result)

#Recency vs Frequency
rfm_rf_plot(rfm_result)

############
rfm_data2<- data.frame(rfm_result_RG$rfm)
head(rfm_data2)

rfm_data2<-arrange(rfm_data2, desc(rfm_data2$rfm_score))
head(rfm_data2)

rfm_top50percent_data_RG <- rfm_data2[1:(nrow(rfm_data2)/2),]

head(rfm_top50percent_data_RG)

head(rfm_top50percent_data_TG)

nrow(rfm_top50percent_data_RG)

nrow(rfm_top50percent_data_TG)

rg_data <- orignalData %>% select(customer_Number, RevenueBand,TotalAmount,Revenue) %>% 
                            filter(customer_Number  %in% rfm_top50percent_data_RG$customer_id)

tg_data <- orignalData %>% select(customer_Number, RevenueBand,TotalAmount, Revenue) %>%
                          filter( customer_Number %in% rfm_top50percent_data_TG$customer_id)

summary(rg_data)
summary(tg_data)

table(rg_data$RevenueBand)
table(tg_data$RevenueBand)


rg_25to50  <-  filter(rg_data, rg_data$RevenueBand == "25-50")
rg_50to75  <-  filter(rg_data, rg_data$RevenueBand == "50-75")
rg_Above75 <- filter(rg_data, rg_data$RevenueBand == "Above 75")
rg_Below25 <- filter(rg_data, rg_data$RevenueBand == "Below 25")

tg_25to50  <-  filter(tg_data, tg_data$RevenueBand == "25-50")
tg_50to75  <-  filter(tg_data, tg_data$RevenueBand == "50-75")
tg_Above75 <- filter(tg_data, tg_data$RevenueBand == "Above 75")
tg_Below25 <- filter(tg_data, tg_data$RevenueBand == "Below 25")

set.seed(420)
tg_25to50_sample = sample_n(tg_25to50, 2450)

set.seed(420)
tg_50to75_sample = sample_n(tg_50to75, 2950)

set.seed(420)
tg_Above75_sample = sample_n(tg_Above75, 3660)

set.seed(420)
tg_Below25_sample = sample_n(tg_Below25, 2120)

tg_data_sample <- rbind(tg_25to50_sample,tg_50to75_sample,tg_Above75_sample,tg_Below25_sample)

```
#t-test
```{r}
############################## t- test #############################


t.test(tg_data_sample$TotalAmount,rg_data$TotalAmount)

```
#STEP 7
```{r}
################################    Step 7    #######################
rg<- table(rg_data$RevenueBand)
tg<-table(tg_data$RevenueBand)
rg<-transform(rg)
tg<-transform(tg)
rg_tg<-cbind(rg,tg)

names(rg_tg)[1]<-"Revenue_Band"
names(rg_tg)[2]<- "RG_total_customers"
names(rg_tg)[4]<- "TG_total_customers"
rg_tg <- rg_tg[,-3]


rg_tg$TG_AvgAmountPerMember <- c(sum(tg_25to50$Revenue)/nrow(tg_25to50),
sum(tg_50to75$Revenue)/nrow(tg_50to75),
sum(tg_Above75$Revenue)/nrow(tg_Above75),
sum(tg_Below25$Revenue)/nrow(tg_Below25))

rg_tg$RG_AvgAmountPerMember <- c(sum(rg_25to50$Revenue)/nrow(rg_25to50),
                               sum(rg_50to75$Revenue)/nrow(rg_50to75),
                               sum(rg_Above75$Revenue)/nrow(rg_Above75),
                               sum(rg_Below25$Revenue)/nrow(rg_Below25))

DT::datatable(rg_tg)

```

